services:
  camoufox:
    build: .
    container_name: camoufox
    restart: always
    ports:
      - "9222:9222"
    expose:
      - "9222"
    environment:
      - CAMOUFOX_PORT: 9222
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true
